MKUchat/MKUchat/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include("home.urls")),
    path('users/', include("users.urls")),
    path('profiles/', include("profiles.urls")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += path('^__debug__/', include(debug_toolbar.urls)),

MKUchat/home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns=[
    path("", views.homepage, name="home"),
    path("welcome", views.welcomepage, name="welcomepage"),
    path("createaccount", views.createaccount, name="createaccount"),
]

MKUchat/users/urls.py
from django.urls import path

from . import views

app_name="users"
urlpatterns=[
    path("", views.registrationpage, name="index"),
     path("login", views.login_views, name="loginpage"),
     path("logout", views.logout_views, name="logoutpage"),

]

MKUchat/users/models.py
from django.db import models

# Create your models here.

MKUchat/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    pass

MKUchat/home/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

def welcomepage(request):
    return render(request, "home/Welcomepage.html")

def loginpage(request):
    return render(request, "home/login.html")

def createaccount(request):
    return HttpResponse("we shoud have the form to create an account here")

def logoutpage(request):
    return HttpResponse("You have succesfully logged out")

def homepage(request):
    return render(request,"home/home.html")

MKUchat/users/views.py
import email
from multiprocessing import context
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from home import *
from django.contrib.auth.models import User, auth

# Create your views here.

def registrationpage(request):

    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if password1 == password2:

            if User.objects.filter(username=username).exists():
                return render(request, "home/login.html", {
                    "message":"Username Already Used"
                })

            elif User.objects.filter(email=email).exists():
                return render(request, "home/login.html", {
                    "message":"Email has already been used"
                })
        
            else:
                user = User.objects.create_user(username=username, password=password1, email=email)
                user.save()
                return render(request, "home/login.html", {
                    "message":"Acoount Created Succesfully! You can now log in"
                })

        else:
            return render(request, "home/login.html", {
            "message":"Password not matching"
            })

    else:
        return render(request, "home/login.html", {
            "message":"Failed. Kindly try again!"
        })

def login_views(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, "home/home.html")
        else:
            return render(request, "home/login.html", {
                "message": "Invalid Credentials"
            })

    return render(request, "home/login.html")

def logout_views(request):
    logout(request)
    return render(request, "home/login.html", {
        "message": "Logged Out."
    })

MKUchat/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Homepage</title>
        <link href="{% static 'home/styles.css' %}" rel="stylesheet">
        <script src="https://kit.fontawesome.com/500d9c8f15.js" crossorigin="anonymous"></script>
    </head>
    <body class="base">

        <nav>
            <div class="nav-left">
                <img src="{% static 'home/mku.png' %}" class="logo" width="">
                <h4 style="color: white; font-size:18px;">MKUchat</h4>
                <ul>
                    <li>
                        <img src="{% static 'home/notification.png' %}">
                        <img src="{% static 'home/inbox.png' %}">
                        <img src="{% static 'home/videoo.png' %}">
                        
                    </li>
                </ul>
            </div>
            <div class="nav-right">
                <div class="search-box">
                    <img src="{% static 'home/search.png' %}">
                    <input type="text" placeholder="Search">
                </div>
                <div class="nav-user-icon online">
                    <img src="{% static 'home/profile-pic.jpg' %}">
                </div>
                <div class="logout">
                    <a href="{% url 'users:logoutpage' %}">LogOut</a>
                </div>
                
            </div>
        </nav>

        {% block body %}
        {% endblock %}
    </body>
</html>

MKUchat/home/templates/home/home.html
{% extends "home/base.html" %}
{% load static %}

{% block body %}

    <div class="container">
        <!-----------left-sidebar---------->
        <div class="left-sidebar">
            <div class="imp-links">
                <a href="#"><img src="{% static 'home/news.png' %}">Latest News</a>
                <a href="{% url 'profiles:friends' %}"><img src="{% static 'home/friends.png' %}"> Friends</a>
                <a href="#"><img src="{% static 'home/group.png' %}"> Group</a>
                <a href="#"><img src="{% static 'home/marketplace.png' %}"> Marketplace</a>
                <a href="#"><img src="{% static 'home/watch.png' %}"> Watch</a>
                <a href="#"> See More</a>
            </div>
            <div class="shortcut-links">
                <p>Your Shortcuts</p>
                <a href="#"><img src="{% static 'home/shortcut-1.png' %}"> BIT Students</a>
                <a href="#"><img src="{% static 'home/shortcut-2.png' %}"> BBIT Students</a>
                <a href="#"><img src="{% static 'home/shortcut-3.png' %}"> BCOM Students</a>
                <a href="#"><img src="{% static 'home/shortcut-4.png' %}"> MKU Lecturers</a>
            </div>
        </div>
        <!-----------main-content---------->
        <div class="main-content">

            <div class="story-gallery">
                <div class="story">
                    <img src="{% static 'home/upload.png' %}" alt="">
                    <p>Post Story</p>
                </div>
                <div class="story">
                    <img src="{% static 'home/shortcut-2.png' %}" alt="">
                    <p>Roger</p>
                </div>
                <div class="story">
                    <img src="{% static 'home/shortcut-3.png' %}" alt="">
                    <p>Gerald</p>
                </div>
                <div class="story">
                    <img src="{% static 'home/shortcut-4.png' %}" alt="">
                    <p>Erick</p>
                </div>
                <div class="story">
                    <img src="{% static 'home/shortcut-2.png' %}" alt="">
                    <p>Khalid</p>
                </div>
            </div>




        </div>
        <!-----------right-sidebar---------->
        <div class="right-sidebar">

            <div class="sidebar-title">
                <h4>Events</h4>
                <a href="#">See All</a>
            </div>

            <div class="event">
                <div class="left-event">
                    <h3>21</h3>
                    <span>June</span>
                </div>
                <div class="right-event">
                    <h4>Graduation</h4>
                    <p><i class="fa-solid fa-location-dot"></i>Convention Center</p>
                    <a href="#">More Info</a>
                </div>
            </div>

            <div class="event">
                <div class="left-event">
                    <h3>25</h3>
                    <span>June</span>
                </div>
                <div class="right-event">
                    <h4>Delegates Elections</h4>
                    <p><i class="fa-solid fa-location-dot"></i>Convention Center</p>
                    <a href="#">More Info</a>
                </div>
            </div>

           <!--<div class="sidebar-title">
                <h4>Advertisement</h4>
                <a href="#">Close</a>
            </div>
            <div class="sidebar-ads">
                <img src="{% static 'home/advertisement.png' %}" >
            </div>---> 
            

            <div class="sidebar-title">
                <h4>Conversation</h4>
                <a href="#">Hide Chat</a>
            </div>

            <div class="online-list">
                <div class="online">
                    <img src="{% static 'home/advertisement.png' %}">
                    <p>Parfait</p>
                </div>
            </div>
            <div class="online-list">
                <div class="online">
                    <img src="{% static 'home/advertisement.png' %}">
                    <p>Gerald</p>
                </div>
            </div>




        </div>



    </div>

{% endblock %}

MKUchat/home/templates/home/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>layout</title>
        <link href="{% static 'home/styles.css' %}" rel="stylesheet">
    </head>
    <body class="welcome">
        {% block1 body %}
        {% endblock1 %}
    </body>
</html>

MKUchat/home/templates/home/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link href="{% static 'home/styles2.css' %}" rel="stylesheet">
  </head>
  <body class="login-signup">
    <div class="main">  	
      <input type="checkbox" id="chk" aria-hidden="true">
          {% if message %}
              <div class="message">{{ message }}</div>
           {% endif %}
  
        <div class="signup">

          <form action="{% url 'users:index' %}" method="post">
            {% csrf_token %}
            <label for="chk" aria-hidden="true">Sign up</label>
            <input type="text" name="username" placeholder="User name" required="">
            <input type="email" name="email" placeholder="Email" required="">
            <input type="password" name="password1" placeholder="Password" required="">
            <input type="password" name="password2" placeholder="Confirm Password" required="">
            <button>Sign up</button>
          </form>
        </div>
  
        <div class="login">

          <form action="{% url 'users:loginpage' %}" method="post">
            {% csrf_token %}
            <label for="chk" aria-hidden="true">Login</label>
            <input type="text" name="username" placeholder="User name" id="username">
            <input type="password" name="password" placeholder="Password" id="password">
            <button>Login</button>
          </form>
        </div>
    </div>
  </body>
</html>

MKUchat/home/templates/home/welcomepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Welcome page</title>
        <link href="{% static 'home/styles.css' %}" rel="stylesheet">
    </head>
    <body class="welcome">
        <h1>Welcome to MKUchat</h1>
        <p>MKUchat is a soial media created to connect MKU students. in order to creat MKUchat Account you 
            must be an MKU student.
        </p>
        <p>If you already have an MKUchat account, kindly click the <strong>Login</strong> button to get access to your 
            account!</p>
        <p>In case you don't have an account, click on <strong>CreateAnAccount</strong>  to create one for free</p>
        <br>
        <a class="button button1" href="{% url 'loginpage' %}">Login</a>
        <a class="button button2" href="{% url 'createaccount' %}">CreateAnAccount</a>
    </body>
</html>